

import React, { useState } from 'react';
import { PayrollResult as PayrollResultType } from '../types';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from './ui/Card';
import { Button } from './ui/Button';
import { PayProgressionChart } from './PayProgressionChart';
import { CareerTimeline } from './CareerTimeline';
import { ExcelIcon, FileCogIcon, PdfIcon, WordIcon } from './ui/Icons';
import { YearlyPayrollAccordion } from './YearlyPayrollAccordion';
import { useLanguage } from './LanguageProvider';
import { Input } from './ui/Input';
import { Label } from './ui/Label';
import { HeroIcon } from './ui/HeroIcon';


// Declare global variables from CDN scripts to satisfy TypeScript
declare global {
    interface Window {
        jspdf: any;
        htmlDocx: any;
        saveAs: (blob: Blob, filename: string) => void;
    }
}
declare const XLSX: any;


interface PayrollResultProps {
  result: PayrollResultType;
}

const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', minimumFractionDigits: 0 }).format(amount);
};

const formatCurrencyForExport = (amount: number) => {
    return `Rs. ${new Intl.NumberFormat('en-IN', { minimumFractionDigits: 0 }).format(amount)}`;
};


const PayrollResult: React.FC<PayrollResultProps> = ({ result }) => {
  const { employeeDetails, fixation4thPC, fixation5thPC, fixation6thPC, fixation7thPC, yearlyCalculations, appliedRevisions, incrementAnalysis } = result;
  const { t } = useLanguage();
  const [isDdoVerified, setIsDdoVerified] = useState(false);
  const [auditorRemarks, setAuditorRemarks] = useState('');
  
  const hasAppliedGO237 = yearlyCalculations.some(year => 
    year.periods.some(p => p.remarks.join(' ').includes('G.O.Ms.No.237/2013'))
  );

  const wasIncrementWithheld = yearlyCalculations.some(year => 
    year.periods.some(p => p.remarks.join(' ').toLowerCase().includes('withheld'))
  );

    const addBilingualFooterToPdf = (doc: any) => {
        const pageCount = doc.internal.getNumberOfPages();
        const footerText = t('bilingualFooter');
        const splitFooter = doc.splitTextToSize(footerText, doc.internal.pageSize.width - 28);
        
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
             doc.text(
                'Generated by Payroll AI System',
                doc.internal.pageSize.width / 2,
                doc.internal.pageSize.height - 20,
                { align: 'center' }
            );
            doc.text(
                splitFooter,
                doc.internal.pageSize.width / 2,
                doc.internal.pageSize.height - 15,
                { align: 'center' }
            );
        }
    };
    
    const handleExportFixationPDF = () => {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();

        doc.setFont('times', 'bold');
        doc.setFontSize(16);
        doc.text('PAY FIXATION STATEMENT', 105, 15, { align: 'center' });

        doc.setFont('times', 'normal');
        doc.setFontSize(12);
        const introText = `As per the relevant Tamil Nadu Revised Pay Rules, the pay for Thiru/Tmt. ${employeeDetails.employeeName}, ${employeeDetails.joiningPost}, is fixed as follows:`;
        const splitIntro = doc.splitTextToSize(introText, 180);
        doc.text(splitIntro, 14, 25);
        
        let lastY = 45;

        if (fixation4thPC) {
             doc.setFont('times', 'bold');
            doc.text('1. Fixation into 4th Pay Commission (w.e.f. 01.01.1986)', 14, lastY);
            const body = [
                ['Basic Pay as on 31.12.1985', formatCurrencyForExport(fixation4thPC.basicPay1986)],
                ['Pay fixed in revised scale', formatCurrencyForExport(fixation4thPC.initialRevisedPay)],
            ];
             doc.autoTable({
                startY: lastY + 4, body: body, theme: 'striped',
                styles: { fontSize: 10, cellPadding: 2.5 },
                columnStyles: { 0: { fontStyle: 'bold', cellWidth: 80 } }
            });
            lastY = (doc as any).lastAutoTable.finalY + 8;
        }
        
        if (fixation5thPC) {
             doc.setFont('times', 'bold');
            doc.text('2. Fixation into 5th Pay Commission (w.e.f. 01.01.1996)', 14, lastY);
            const body = [
                ['Basic Pay as on 31.12.1995', formatCurrencyForExport(fixation5thPC.basicPay1995)],
                ['Total existing emoluments', formatCurrencyForExport(fixation5thPC.totalPay)],
                [{ content: 'Pay fixed in revised scale', styles: { fontStyle: 'bold' } }, { content: formatCurrencyForExport(fixation5thPC.initialRevisedPay), styles: { fontStyle: 'bold' } }],
            ];
             doc.autoTable({
                startY: lastY + 4, body: body, theme: 'striped',
                styles: { fontSize: 10, cellPadding: 2.5 },
                columnStyles: { 0: { fontStyle: 'bold', cellWidth: 80 } }
            });
            lastY = (doc as any).lastAutoTable.finalY + 8;
        }

        if (fixation6thPC) {
            doc.setFont('times', 'bold');
            doc.text('3. Fixation into 6th Pay Commission (w.e.f. 01.01.2006)', 14, lastY);
            const body = [
                ['Basic Pay as on 31.12.2005', formatCurrencyForExport(fixation6thPC.basicPay2005)],
                ['Pay after multiplication by Fitment Factor of 1.86', formatCurrencyForExport(fixation6thPC.multipliedPay)],
                ['Pay in the revised Pay Band (PB)', formatCurrencyForExport(fixation6thPC.initialPayInPayBand)],
                ['Applicable Grade Pay (GP)', formatCurrencyForExport(fixation6thPC.initialGradePay)],
                [{ content: 'Revised Basic Pay (PB + GP)', styles: { fontStyle: 'bold' } }, { content: formatCurrencyForExport(fixation6thPC.initialRevisedBasicPay), styles: { fontStyle: 'bold' } }],
            ];
             doc.autoTable({
                startY: lastY + 4,
                body: body,
                theme: 'striped',
                styles: { fontSize: 10, cellPadding: 2.5 },
                columnStyles: { 0: { fontStyle: 'bold', cellWidth: 80 } }
            });
            lastY = (doc as any).lastAutoTable.finalY;
        }
        
        if (fixation7thPC) {
            const startY = lastY + 12;
            doc.setFont('times', 'bold');
            doc.text('4. Fixation into 7th Pay Commission (w.e.f. 01.01.2016)', 14, startY);
            const body = [
                ['Basic Pay as on 31.12.2015', formatCurrencyForExport(fixation7thPC.oldBasicPay)],
                ['Pay after multiplication by Fitment Factor of 2.57', formatCurrencyForExport(fixation7thPC.multipliedPay)],
                ['Applicable Level in Pay Matrix', `Level ${fixation7thPC.level}`],
                [{ content: 'Revised Pay in the applicable Level', styles: { fontStyle: 'bold' } }, { content: formatCurrencyForExport(fixation7thPC.initialRevisedPay), styles: { fontStyle: 'bold' } }],
            ];
            doc.autoTable({
                startY: startY + 4,
                body: body,
                theme: 'striped',
                styles: { fontSize: 10, cellPadding: 2.5 },
                columnStyles: { 0: { fontStyle: 'bold', cellWidth: 80 } }
            });
            lastY = (doc as any).lastAutoTable.finalY;
        }

        doc.setFont('times', 'normal');
        doc.text('Signature of Head of Office / Department', 195, lastY + 30, { align: 'right' });

        addBilingualFooterToPdf(doc);
        doc.save(`PayFixation_${employeeDetails.employeeName.replace(' ', '_')}.pdf`);
    };


    const handleExportPDF = () => {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();
        
        doc.setFontSize(18);
        doc.text('Payroll Calculation Report', 14, 22);

        // Employee Summary
        let summaryBody = [
            ['Employee Name', employeeDetails.employeeName],
            ["Father's Name", employeeDetails.fatherName],
            ['Employee Number', employeeDetails.employeeNo],
            ['CPS / GPF No.', employeeDetails.cpsGpfNo],
            ['PAN Number', employeeDetails.panNumber],
            ['Bank Account No.', employeeDetails.bankAccountNumber],
            ['Date of Birth', employeeDetails.dateOfBirth],
            ['Date of Joining (Service)', employeeDetails.dateOfJoining],
            ['Date of Joining (Office)', employeeDetails.dateOfJoiningInOffice],
            ['Date of Relief (Transfer)', employeeDetails.dateOfRelief || 'N/A'],
            ['Post at Joining', employeeDetails.joiningPost || 'N/A'],
            ['Date of Retirement', employeeDetails.retirementDate],
        ];

        employeeDetails.promotions.forEach((promo, i) => {
            summaryBody.push([`Promotion ${i+1} Post`, promo.post || 'N/A']);
            summaryBody.push([`Promotion ${i+1} Date`, promo.date || 'N/A']);
        });

        doc.setFontSize(12);
        doc.text('Employee Summary', 14, 32);
        doc.autoTable({
            startY: 36,
            body: summaryBody,
            theme: 'striped',
            styles: { fontSize: 8 },
        });

        // Pay Fixations
        let lastTableY = (doc as any).lastAutoTable.finalY + 10;
        if (fixation4thPC || fixation5thPC || fixation6thPC || fixation7thPC) {
            doc.text('Initial Pay Fixations', 14, lastTableY);
            const fixationBody = [];
             if(fixation4thPC) {
                fixationBody.push([`4th PC (01-01-1986)`, formatCurrencyForExport(fixation4thPC.basicPay1986), '-', '-', formatCurrencyForExport(fixation4thPC.initialRevisedPay)]);
            }
            if(fixation5thPC) {
                fixationBody.push([`5th PC (01-01-1996)`, formatCurrencyForExport(fixation5thPC.basicPay1995), '-', formatCurrencyForExport(fixation5thPC.totalPay), formatCurrencyForExport(fixation5thPC.initialRevisedPay)]);
            }
            if(fixation6thPC) {
                fixationBody.push([`6th PC (01-01-2006)`, formatCurrencyForExport(fixation6thPC.basicPay2005), 'x 1.86', `${formatCurrencyForExport(fixation6thPC.initialPayInPayBand)} (PIPB)`, `${formatCurrencyForExport(fixation6thPC.initialRevisedBasicPay)}`]);
            }
            if(fixation7thPC) {
                 fixationBody.push([`7th PC (01-01-2016)`, formatCurrencyForExport(fixation7thPC.oldBasicPay), 'x 2.57', formatCurrencyForExport(fixation7thPC.multipliedPay), `${formatCurrencyForExport(fixation7thPC.initialRevisedPay)} (Lvl ${fixation7thPC.level})`]);
            }
            doc.autoTable({
                startY: lastTableY + 4,
                head: [['Commission', 'Old Basic Pay', 'Factor', 'Intermediate Pay', 'New Basic Pay']],
                body: fixationBody,
                theme: 'grid',
                styles: { fontSize: 8 },
            });
        }

        // Yearly Calculations
        yearlyCalculations.forEach(yearData => {
            lastTableY = (doc as any).lastAutoTable.finalY + 10;
            doc.text(`Payroll for ${yearData.year}`, 14, lastTableY);
            const tableBody = yearData.periods.flatMap(p => [
              [p.period, formatCurrencyForExport(p.basicPay), `${formatCurrencyForExport(p.daAmount)} (${p.daRate}%)`, formatCurrencyForExport(p.hra), formatCurrencyForExport(p.grossPay), formatCurrencyForExport(p.totalDeductions), formatCurrencyForExport(p.netPay)],
              p.remarks.length > 0 ? [{ content: `Note: ${p.remarks.join(' ')}`, colSpan: 7, styles: { fontStyle: 'italic', fontSize: 7 } }] : []
            ]);
            doc.autoTable({
                startY: lastTableY + 4,
                head: [['Period', 'Basic Pay', 'DA', 'HRA', 'Gross Pay', 'Deductions', 'Net Pay']],
                body: tableBody,
                theme: 'striped',
                styles: { fontSize: 8 },
            });
        });

        addBilingualFooterToPdf(doc);
        doc.save(`Payroll_Report_${employeeDetails.employeeName.replace(' ', '_')}.pdf`);
    };
    
    const handleExportPaySlip = () => {
        if (yearlyCalculations.length === 0 || yearlyCalculations[yearlyCalculations.length - 1].periods.length === 0) {
            alert("No calculation data available to generate a payslip.");
            return;
        }

        const lastYear = yearlyCalculations[yearlyCalculations.length - 1];
        const lastPeriod = lastYear.periods[lastYear.periods.length - 1];

        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();

        // Header
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(16);
        doc.text('Government of Tamil Nadu', 105, 15, { align: 'center' });
        doc.setFontSize(12);
        doc.text(`Pay Slip for ${lastPeriod.period}`, 105, 22, { align: 'center' });
        doc.line(14, 25, 196, 25);

        // Employee Details
        const empDetailsBody = [
            ['Employee Name', employeeDetails.employeeName, 'Employee No.', employeeDetails.employeeNo],
            ['Designation', employeeDetails.joiningPost, 'CPS/GPF No.', employeeDetails.cpsGpfNo],
            ['PAN', employeeDetails.panNumber, 'Bank A/C No.', employeeDetails.bankAccountNumber],
        ];
        doc.autoTable({
            startY: 28,
            body: empDetailsBody,
            theme: 'plain',
            styles: { fontSize: 9, cellPadding: 1.5 },
        });
        let lastY = (doc as any).lastAutoTable.finalY;

        // Earnings and Deductions
        const earningsBody = [
            ['Basic Pay', formatCurrencyForExport(lastPeriod.basicPay)],
            ['Dearness Allowance', formatCurrencyForExport(lastPeriod.daAmount)],
            ['House Rent Allowance', formatCurrencyForExport(lastPeriod.hra)],
            ['City Compensatory Allowance', formatCurrencyForExport(lastPeriod.cca)],
            ['Medical Allowance', formatCurrencyForExport(lastPeriod.medicalAllowance)],
        ];
        const deductionsBody = lastPeriod.deductions.map(d => [d.name, formatCurrencyForExport(d.amount)]);
        
        doc.autoTable({
            startY: lastY + 2,
            head: [['Earnings', 'Amount']],
            body: earningsBody,
            theme: 'striped',
            styles: { fontSize: 9 },
            columnStyles: { 1: { halign: 'right' } },
            tableWidth: 90,
            margin: { left: 14 }
        });
        
        doc.autoTable({
            startY: lastY + 2,
            head: [['Deductions', 'Amount']],
            body: deductionsBody,
            theme: 'striped',
            styles: { fontSize: 9 },
            columnStyles: { 1: { halign: 'right' } },
            tableWidth: 90,
            margin: { left: 106 }
        });

        // Totals
        const totalsBody = [
            [{ content: 'Gross Pay', styles: { fontStyle: 'bold' } }, { content: formatCurrencyForExport(lastPeriod.grossPay), styles: { fontStyle: 'bold', halign: 'right' } }],
            [{ content: 'Total Deductions', styles: { fontStyle: 'bold' } }, { content: formatCurrencyForExport(lastPeriod.totalDeductions), styles: { fontStyle: 'bold', halign: 'right' } }],
        ];

        doc.autoTable({
            startY: (doc as any).lastAutoTable.finalY,
            body: totalsBody,
            theme: 'grid',
            styles: { fontSize: 9, cellPadding: 2, fillColor: [230, 240, 255] },
            tableWidth: 182,
            margin: { left: 14 }
        });
        lastY = (doc as any).lastAutoTable.finalY;

        // Net Pay
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text('Net Pay:', 15, lastY + 10);
        doc.text(formatCurrencyForExport(lastPeriod.netPay), 195, lastY + 10, { align: 'right' });
        
        const netInWords = `(Rupees ${t('amountInWords', { amount: lastPeriod.netPay })} Only)`; // Assuming a helper exists
        doc.setFontSize(9);
        doc.setFont('helvetica', 'italic');
        // doc.text(netInWords, 15, lastY + 15);


        addBilingualFooterToPdf(doc);
        doc.save(`PaySlip_${lastPeriod.period.replace(' ', '')}_${employeeDetails.employeeName}.pdf`);
    };

    const handleExportLPC = () => {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();
        const { festivalAdvance, carAdvance, twoWheelerAdvance, computerAdvance, otherPayables } = employeeDetails;

        doc.setFont('times', 'bold');
        doc.setFontSize(14);
        doc.text('LAST PAY CERTIFICATE', 105, 15, { align: 'center' });
        
        doc.setFont('times', 'normal');
        doc.setFontSize(12);
        const introText = `Certified that the following are the particulars of Pay and Allowances drawn by Thiru/Tmt. ${employeeDetails.employeeName}, ${employeeDetails.joiningPost}, who has been relieved from this office on the afternoon of ${employeeDetails.dateOfRelief} to join another post.`;
        const splitIntro = doc.splitTextToSize(introText, 180);
        doc.text(splitIntro, 14, 25);
        
        let lastY = 40;

        // Pay and Allowances drawn
        const lastYear = yearlyCalculations[yearlyCalculations.length - 1];
        const lastPeriod = lastYear.periods[lastYear.periods.length - 1];
        
        doc.setFont('times', 'bold');
        doc.text('1. Rate of Pay and Allowances Drawn:', 14, lastY + 10);
        const payBody = [
            ['Basic Pay', formatCurrencyForExport(lastPeriod.basicPay)],
            ['Dearness Allowance', `${formatCurrencyForExport(lastPeriod.daAmount)} (${lastPeriod.daRate}%)`],
            ['House Rent Allowance', formatCurrencyForExport(lastPeriod.hra)],
            [{ content: 'Gross Pay', styles: { fontStyle: 'bold' } }, { content: formatCurrencyForExport(lastPeriod.grossPay), styles: { fontStyle: 'bold' } }],
        ];
        doc.autoTable({
            startY: lastY + 14,
            body: payBody,
            theme: 'striped',
            styles: { fontSize: 10, cellPadding: 2 },
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60 } }
        });
        lastY = (doc as any).lastAutoTable.finalY;
        
        // Deductions/Advances
        doc.setFont('times', 'bold');
        doc.text('2. Outstanding Long Term Advances:', 14, lastY + 10);
        const advancesBody = [];
        if (festivalAdvance) advancesBody.push(['Festival Advance', formatCurrencyForExport(festivalAdvance)]);
        if (carAdvance) advancesBody.push(['Car Advance', formatCurrencyForExport(carAdvance)]);
        if (twoWheelerAdvance) advancesBody.push(['Two-Wheeler Advance', formatCurrencyForExport(twoWheelerAdvance)]);
        if (computerAdvance) advancesBody.push(['Computer Advance', formatCurrencyForExport(computerAdvance)]);
        if (otherPayables) advancesBody.push(['Other Payables / Dues', formatCurrencyForExport(otherPayables)]);
        
        if (advancesBody.length > 0) {
            doc.autoTable({
                startY: lastY + 14,
                head: [['Advance / Payable Type', 'Outstanding Amount']],
                body: advancesBody,
                theme: 'grid',
                styles: { fontSize: 10, cellPadding: 2 },
            });
            lastY = (doc as any).lastAutoTable.finalY;
        } else {
            doc.setFont('times', 'normal');
            doc.text('NIL', 20, lastY + 20);
            lastY += 20;
        }

        const conclusionText = `He/She has been paid up to ${employeeDetails.dateOfRelief}. The details of deductions towards GPF/CPS, Professional Tax, and other subscriptions are recorded in his/her Service Book.`;
        const splitConclusion = doc.splitTextToSize(conclusionText, 180);
        doc.setFont('times', 'normal');
        doc.text(splitConclusion, 14, lastY + 15);
        
        doc.text('Signature of Drawing and Disbursing Officer', 195, lastY + 45, { align: 'right' });

        addBilingualFooterToPdf(doc);
        doc.save(`LPC_${employeeDetails.employeeName.replace(' ', '_')}.pdf`);
    };

    const handleExportExcel = () => {
      const wb = XLSX.utils.book_new();
      
      // Summary Sheet
      let summaryData = [
        ['Employee Name', employeeDetails.employeeName],
        ["Father's Name", employeeDetails.fatherName],
        ['Employee Number', employeeDetails.employeeNo],
        ['CPS / GPF No.', employeeDetails.cpsGpfNo],
        ['PAN Number', employeeDetails.panNumber],
        ['Bank Account No.', employeeDetails.bankAccountNumber],
        ['Date of Birth', employeeDetails.dateOfBirth],
        ['Date of Joining (Service)', employeeDetails.dateOfJoining],
        ['Date of Joining (Office)', employeeDetails.dateOfJoiningInOffice],
        ['Date of Relief (Transfer)', employeeDetails.dateOfRelief || 'N/A'],
        ['Post at Joining', employeeDetails.joiningPost || 'N/A'],
        ['Date of Retirement', employeeDetails.retirementDate],
      ];
      employeeDetails.promotions.forEach((promo, i) => {
            summaryData.push([`Promotion ${i+1} Post`, promo.post || 'N/A']);
            summaryData.push([`Promotion ${i+1} Date`, promo.date || 'N/A']);
      });

      const fixationHeader = [ [], ['Pay Fixation Details'], ['Commission', 'Old Basic Pay', 'Factor', 'Intermediate Pay', 'New Basic Pay']];
      const fixationData = [];
        if(fixation4thPC) {
            fixationData.push([`4th PC (01-01-1986)`, fixation4thPC.basicPay1986, '-', '-', fixation4thPC.initialRevisedPay]);
        }
        if(fixation5thPC) {
            fixationData.push([`5th PC (01-01-1996)`, fixation5thPC.basicPay1995, '-', fixation5thPC.totalPay, fixation5thPC.initialRevisedPay]);
        }
       if(fixation6thPC) {
            fixationData.push([`6th PC (01-01-2006)`, fixation6thPC.basicPay2005, 'x 1.86', `${fixation6thPC.initialPayInPayBand} (PIPB)`, fixation6thPC.initialRevisedBasicPay]);
        }
        if(fixation7thPC) {
            fixationData.push([`7th PC (01-01-2016)`, fixation7thPC.oldBasicPay, 'x 2.57', fixation7thPC.multipliedPay, `${fixation7thPC.initialRevisedPay} (Lvl ${fixation7thPC.level})`]);
        }
      
      const ws_summary = XLSX.utils.aoa_to_sheet([...summaryData, ...fixationHeader, ...fixationData]);
      XLSX.utils.book_append_sheet(wb, ws_summary, 'Summary');

      // Yearly Data
      const allPeriods = yearlyCalculations.flatMap(yearData => 
        yearData.periods.map(p => ({
          'Year': yearData.year,
          'Period': p.period,
          'Basic Pay': p.basicPay,
          'DA Rate (%)': p.daRate,
          'DA Amount': p.daAmount,
          'HRA': p.hra,
          'CCA': p.cca,
          'Medical Allowance': p.medicalAllowance,
          'Gross Pay': p.grossPay,
          'Total Deductions': p.totalDeductions,
          'Net Pay': p.netPay,
          'Remarks': p.remarks.join(' '),
        }))
      );
      const ws_details = XLSX.utils.json_to_sheet(allPeriods);
      XLSX.utils.book_append_sheet(wb, ws_details, 'Detailed Payroll');
      
       // Add footer row
      const footer = [t('bilingualFooter')];
      XLSX.utils.sheet_add_aoa(ws_details, [[]], {origin: -1}); // Add a blank row for spacing
      XLSX.utils.sheet_add_aoa(ws_details, [footer], {origin: -1});


      XLSX.writeFile(wb, `Payroll_Report_${employeeDetails.employeeName.replace(' ', '_')}.xlsx`);
    };

    const handleExportWord = async () => {
        if (!window.htmlDocx || !window.saveAs) {
            alert("A required library (html-to-docx or FileSaver) failed to load. Please check your internet connection and try again.");
            console.error("`window.htmlDocx` or `window.saveAs` is not available. The scripts might have failed to load.");
            return;
        }

        let promotionHtml = employeeDetails.promotions.map((p,i) => `
            <tr><td>Promotion ${i+1} Post</td><td>${p.post || 'N/A'}</td></tr>
            <tr><td>Promotion ${i+1} Date</td><td>${p.date || 'N/A'}</td></tr>
        `).join('');

        let fixationHtml = '';
        if (fixation4thPC || fixation5thPC || fixation6thPC || fixation7thPC) {
            fixationHtml += `<h2>Initial Pay Fixations</h2>
          <table>
            <thead><tr><th>Commission</th><th>Old Basic Pay</th><th>Factor</th><th>Intermediate Pay</th><th>New Basic Pay</th></tr></thead>
            <tbody>`;
            if (fixation4thPC) {
                 fixationHtml += `<tr><td>4th PC (01-01-1986)</td><td>${formatCurrencyForExport(fixation4thPC.basicPay1986)}</td><td>-</td><td>-</td><td>${formatCurrencyForExport(fixation4thPC.initialRevisedPay)}</td></tr>`;
            }
             if (fixation5thPC) {
                 fixationHtml += `<tr><td>5th PC (01-01-1996)</td><td>${formatCurrencyForExport(fixation5thPC.basicPay1995)}</td><td>-</td><td>${formatCurrencyForExport(fixation5thPC.totalPay)}</td><td>${formatCurrencyForExport(fixation5thPC.initialRevisedPay)}</td></tr>`;
            }
            if (fixation6thPC) {
                 fixationHtml += `<tr><td>6th PC (01-01-2006)</td><td>${formatCurrencyForExport(fixation6thPC.basicPay2005)}</td><td>x 1.86</td><td>${formatCurrencyForExport(fixation6thPC.initialPayInPayBand)} (PIPB)</td><td>${formatCurrencyForExport(fixation6thPC.initialRevisedBasicPay)}</td></tr>`;
            }
            if (fixation7thPC) {
                fixationHtml += `<tr><td>7th PC (01-01-2016)</td><td>${formatCurrencyForExport(fixation7thPC.oldBasicPay)}</td><td>x 2.57</td><td>${formatCurrencyForExport(fixation7thPC.multipliedPay)}</td><td>${formatCurrencyForExport(fixation7thPC.initialRevisedPay)} (Lvl ${fixation7thPC.level})</td></tr>`;
            }
            fixationHtml += '</tbody></table>';
        }

        let htmlString = `
          <style>
            body { font-family: Arial, sans-serif; font-size: 10pt; }
            h1 { font-size: 16pt; }
            h2 { font-size: 12pt; border-bottom: 1px solid #ccc; padding-bottom: 4px; margin-top: 20px;}
            table { border-collapse: collapse; width: 100%; font-size: 9pt; }
            th, td { border: 1px solid #dddddd; text-align: left; padding: 8px; }
            th { background-color: #f2f2f2; }
            .summary-table td:first-child { font-weight: bold; width: 150px; }
            .footer { font-size: 8pt; color: #888; text-align: center; margin-top: 30px; border-top: 1px solid #ccc; padding-top: 10px; }
          </style>
          <h1>Payroll Calculation Report</h1>
          <h2>Employee Summary</h2>
          <table class="summary-table">
            <tr><td>Employee Name</td><td>${employeeDetails.employeeName}</td></tr>
            <tr><td>Father's Name</td><td>${employeeDetails.fatherName}</td></tr>
            <tr><td>Employee Number</td><td>${employeeDetails.employeeNo}</td></tr>
            <tr><td>CPS / GPF No.</td><td>${employeeDetails.cpsGpfNo}</td></tr>
            <tr><td>PAN Number</td><td>${employeeDetails.panNumber}</td></tr>
            <tr><td>Bank Account No.</td><td>${employeeDetails.bankAccountNumber}</td></tr>
            <tr><td>Date of Birth</td><td>${employeeDetails.dateOfBirth}</td></tr>
            <tr><td>Date of Joining (Service)</td><td>${employeeDetails.dateOfJoining}</td></tr>
            <tr><td>Date of Joining (Office)</td><td>${employeeDetails.dateOfJoiningInOffice}</td></tr>
            <tr><td>Date of Relief (Transfer)</td><td>${employeeDetails.dateOfRelief || 'N/A'}</td></tr>
            <tr><td>Post at Joining</td><td>${employeeDetails.joiningPost || 'N/A'}</td></tr>
            <tr><td>Date of Retirement</td><td>${employeeDetails.retirementDate}</td></tr>
            ${promotionHtml}
          </table>
          ${fixationHtml}
        `;
        
        yearlyCalculations.forEach(yearData => {
            htmlString += `<h2>Payroll for ${yearData.year}</h2><table>
                <thead><tr><th>Period</th><th>Basic</th><th>DA</th><th>HRA</th><th>CCA</th><th>Med.</th><th>Gross</th><th>Deduct.</th><th>Net</th><th>Remarks</th></tr></thead>
                <tbody>`;
            yearData.periods.forEach(p => {
                htmlString += `<tr>
                    <td>${p.period}</td>
                    <td>${formatCurrencyForExport(p.basicPay)}</td>
                    <td>${formatCurrencyForExport(p.daAmount)} (${p.daRate}%)</td>
                    <td>${formatCurrencyForExport(p.hra)}</td>
                    <td>${formatCurrencyForExport(p.cca)}</td>
                    <td>${formatCurrencyForExport(p.medicalAllowance)}</td>
                    <td>${formatCurrencyForExport(p.grossPay)}</td>
                    <td>${formatCurrencyForExport(p.totalDeductions)}</td>
                    <td>${formatCurrencyForExport(p.netPay)}</td>
                    <td>${p.remarks.join(' ')}</td>
                </tr>`;
            });
            htmlString += `</tbody></table>`;
        });
        
        htmlString += `<div class="footer"><p>Generated by Payroll AI System</p><p>${t('bilingualFooter')}</p></div>`;

        const blob = await window.htmlDocx.asBlob(htmlString);
        window.saveAs(blob, `Payroll_Report_${employeeDetails.employeeName.replace(' ', '_')}.docx`);
    };

  return (
    <div className="space-y-6">
       <Card>
        <CardHeader className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <CardTitle>{t('employeeSummary')}</CardTitle>
            <CardDescription>{t('reportAndExport')}</CardDescription>
          </div>
          <div className="flex flex-wrap gap-2">
            <Button onClick={handleExportPaySlip} size="sm" className="bg-blue-600 hover:bg-blue-700">{t('generatePaySlip')}</Button>
            {employeeDetails.dateOfRelief && (
                <Button onClick={handleExportLPC} size="sm" className="bg-green-600 hover:bg-green-700">{t('exportLPC')}</Button>
            )}
             <Button onClick={handleExportFixationPDF} variant="outline" size="sm"><FileCogIcon />{t('exportFixation')}</Button>
             <Button onClick={handleExportPDF} variant="outline" size="sm"><PdfIcon />{t('exportReportPDF')}</Button>
             <Button onClick={handleExportExcel} variant="outline" size="sm"><ExcelIcon />{t('exportExcel')}</Button>
             <Button onClick={handleExportWord} variant="outline" size="sm"><WordIcon />{t('exportWord')}</Button>
          </div>
        </CardHeader>
        <CardContent className="grid grid-cols-2 md:grid-cols-3 gap-y-4 gap-x-2 text-sm">
            <div><p className="text-gray-500">{t('employeeName')}</p><p className="font-semibold">{employeeDetails.employeeName || 'N/A'}</p></div>
            <div><p className="text-gray-500">{t('fatherName')}</p><p className="font-semibold">{employeeDetails.fatherName || 'N/A'}</p></div>
            <div><p className="text-gray-500">{t('employeeNo')}</p><p className="font-semibold">{employeeDetails.employeeNo || 'N/A'}</p></div>
            <div><p className="text-gray-500">{t('cpsGpfNo')}</p><p className="font-semibold">{employeeDetails.cpsGpfNo || 'N/A'}</p></div>
            <div><p className="text-gray-500">{t('panNumber')}</p><p className="font-semibold">{employeeDetails.panNumber || 'N/A'}</p></div>
            <div><p className="text-gray-500">{t('bankAccountNumber')}</p><p className="font-semibold">{employeeDetails.bankAccountNumber || 'N/A'}</p></div>
            <div><p className="text-gray-500">{t('dateOfBirth')}</p><p className="font-semibold">{employeeDetails.dateOfBirth || 'N/A'}</p></div>
            <div><p className="text-gray-500">{t('dateOfJoiningService')}</p><p className="font-semibold">{employeeDetails.dateOfJoining || 'N/A'}</p></div>
            <div><p className="text-gray-500">{t('dateOfJoiningOffice')}</p><p className="font-semibold">{employeeDetails.dateOfJoiningInOffice || 'N/A'}</p></div>
            <div><p className="text-gray-500">{t('dateOfRelief')}</p><p className="font-semibold">{employeeDetails.dateOfRelief || 'N/A'}</p></div>
            <div><p className="text-gray-500">{t('postAtJoining')}</p><p className="font-semibold">{employeeDetails.joiningPost || 'N/A'}</p></div>
            <div><p className="text-gray-500">{t('calculatedRetirementDate')}</p><p className="font-semibold">{employeeDetails.retirementDate || 'N/A'}</p></div>
            {employeeDetails.selectionGradeDate && <div><p className="text-gray-500">{t('selectionGradeDate')}</p><p className="font-semibold">{employeeDetails.selectionGradeDate}</p></div>}
            {employeeDetails.specialGradeDate && <div><p className="text-gray-500">{t('specialGradeDate')}</p><p className="font-semibold">{employeeDetails.specialGradeDate}</p></div>}
            {employeeDetails.promotions.map((promo, index) => (
                <React.Fragment key={index}>
                    <div className="col-span-1">
                        <p className="text-gray-500">{t('promotions')} {index + 1}</p>
                        <p className="font-semibold">{promo.post || 'N/A'}</p>
                    </div>
                     <div className="col-span-2">
                           <p className="text-gray-500">{t('dateOfPromotion')}</p>
                           <p className="font-semibold">{promo.date}</p>
                    </div>
                </React.Fragment>
            ))}
            {employeeDetails.accountTestPasses && employeeDetails.accountTestPasses.map((at, index) => (
                 <div key={index} className="col-span-full">
                    <p className="text-gray-500">{t('accountTestPass')} #{index+1}</p>
                    <p className="font-semibold">{at.description} on {at.passDate}</p>
                 </div>
            ))}
        </CardContent>
      </Card>
      
      {wasIncrementWithheld && (
        <Card className="bg-yellow-50 border-yellow-400">
            <CardHeader>
                <CardTitle className="text-yellow-800">{t('incrementAlert')}</CardTitle>
            </CardHeader>
            <CardContent>
                <p className="text-sm text-yellow-700">{t('incrementWithheldMessage')}</p>
            </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
            <CardTitle>{t('probationSummary')}</CardTitle>
        </CardHeader>
        <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
            <div><p className="text-gray-500">{t('probationPeriod')}</p><p className="font-semibold">{employeeDetails.probationPeriod || 'N/A'}</p></div>
            <div><p className="text-gray-500">{t('probationEndsOn')}</p><p className="font-semibold">{employeeDetails.probationEndsOn || 'N/A'}</p></div>
            <div className="col-span-full"><p className="text-gray-500">{t('testRequirementDetails')}</p><p className="font-semibold">{employeeDetails.testDetails || 'N/A'}</p></div>
        </CardContent>
      </Card>
       
      {incrementAnalysis && (
        <Card>
            <CardHeader>
                <CardTitle>{t('incrementAnalysisTitle')}</CardTitle>
            </CardHeader>
            <CardContent className="grid grid-cols-2 md:grid-cols-3 gap-4 text-sm">
                <div><p className="text-gray-500">{t('regularIncrements')}</p><p className="font-semibold text-xl">{incrementAnalysis.regular}</p></div>
                <div><p className="text-gray-500">{t('promotionIncrements')}</p><p className="font-semibold text-xl">{incrementAnalysis.promotion}</p></div>
                <div><p className="text-gray-500">{t('gradeIncrements')}</p><p className="font-semibold text-xl">{incrementAnalysis.selectionGrade + incrementAnalysis.specialGrade}</p></div>
                <div><p className="text-gray-500">{t('accountTestIncrements')}</p><p className="font-semibold text-xl">{incrementAnalysis.accountTest}</p></div>
                <div className="md:col-start-3"><p className="text-gray-500">{t('totalIncrements')}</p><p className="font-bold text-2xl text-emerald-600">{incrementAnalysis.total}</p></div>
            </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
            <CardTitle>{t('auditAndVerification')}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
            <div>
                <Label htmlFor="auditorRemarks">{t('auditorRemarks')}</Label>
                <Input as="textarea" rows={3} id="auditorRemarks" value={auditorRemarks} onChange={(e: any) => setAuditorRemarks(e.target.value)} placeholder={t('auditorRemarksPlaceholder')} />
            </div>
            <div className="flex items-center space-x-2">
                <input type="checkbox" id="ddoVerified" checked={isDdoVerified} onChange={() => setIsDdoVerified(!isDdoVerified)} className="h-4 w-4 rounded border-gray-300 text-emerald-600 focus:ring-emerald-500" />
                <Label htmlFor="ddoVerified" className="mb-0">{t('ddoVerificationCheckbox')}</Label>
            </div>
            {isDdoVerified && <p className="text-sm font-semibold text-green-600">✅ {t('checkedAndVerified')}</p>}
        </CardContent>
      </Card>
      
      {hasAppliedGO237 && (
        <Card>
            <CardHeader>
                <CardTitle>{t('go237Title')}</CardTitle>
            </CardHeader>
            <CardContent>
                <p className="text-sm text-gray-700">{t('go237Message')}</p>
            </CardContent>
        </Card>
      )}

      {appliedRevisions && appliedRevisions.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>{t('payRevisionSummary')}</CardTitle>
            <CardDescription>{t('payRevisionDesc')}</CardDescription>
          </CardHeader>
          <CardContent>
            <ul className="list-disc pl-5 space-y-2 text-sm text-gray-700">
              {appliedRevisions.map((rev, index) => (
                <li key={index}>
                  <span className="font-semibold">{rev.date.toLocaleDateString('en-GB', { timeZone: 'UTC' })}:</span> {rev.description}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
        <PayProgressionChart yearlyCalculations={yearlyCalculations} />
        <CareerTimeline result={result} />
      </div>

      <YearlyPayrollAccordion yearlyCalculations={yearlyCalculations} />
    </div>
  );
};

export default PayrollResult;